application: remindmebmh
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: css
- url: /img
  static_dir: img
- url: /js
  static_dir: js
- url: /reg
  script: models.app
- url: /reg/.*
  script: models.app
- url: /login
  script: models.app
- url: /login/.*
  script: models.app
- url: /.*
  script: helloworld.app

